### PR TITLE
modulesync 0.16.3

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
we need a .sync.yml here

**Comment by alexjfisher** [comment]
You'll also need lint fixes. Ta-dah! https://github.com/voxpupuli/puppet-smokeping/pull/53

**Comment by igalic** [comment]
rebase here?

**Comment by dhoppe** [comment]
Hm. This module does not have any unit or acceptance tests.

**Comment by alexjfisher** [comment]
@dhoppe Yeah, I saw that.  Perhaps open a ticket for somebody to add some?  Even a couple of really basic tests would be better than nothing.

**Comment by alexjfisher** [comment]
https://github.com/voxpupuli/puppet-smokeping/issues/54

**Pull request merged**
